use_frameworks!

target 'Deftoggle_Example' do
  pod 'Deftoggle', :path => '../'
end

target 'Deftoggle_Tests' do
  pod 'Deftoggle', :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end

post_install do |installer|
  target = installer.pods_project.targets.find { |target| target.name == 'Deftoggle' }
  debug_config = target.build_configurations.find { |config| config.name == 'Debug' }
  debug_config.build_settings['ENABLE_TESTABILITY'] = 'YES'
end
